from __future__ import annotations

EXCLUDED_DIRECTORIES = {
    ".git",
    ".hg",
    ".idea",
    ".mypy_cache",
    ".next",
    ".nuxt",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "env",
    "generated",
    "gen",
    "node_modules",
    "out",
    "target",
    "third_party",
    "tmp",
    "vendor",
    "venv",
}

LOCKFILES = {
    "bun.lockb",
    "cargo.lock",
    "composer.lock",
    "package-lock.json",
    "pipfile.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "yarn.lock",
}

BINARY_EXTENSIONS = {
    ".7z",
    ".a",
    ".bin",
    ".class",
    ".crt",
    ".csr",
    ".der",
    ".dll",
    ".dylib",
    ".exe",
    ".gif",
    ".gz",
    ".ico",
    ".jar",
    ".jpeg",
    ".jpg",
    ".key",
    ".mp3",
    ".mp4",
    ".mov",
    ".o",
    ".otf",
    ".pdf",
    ".pem",
    ".png",
    ".pyc",
    ".so",
    ".tar",
    ".ttf",
    ".wav",
    ".webm",
    ".webp",
    ".woff",
    ".woff2",
    ".zip",
}

README_NAMES = {"readme", "readme.md", "readme.rst", "readme.txt"}

MANIFEST_FILE_NAMES = {
    "build.gradle",
    "build.gradle.kts",
    "cargo.toml",
    "composer.json",
    "docker-compose.yml",
    "docker-compose.yaml",
    "dockerfile",
    "go.mod",
    "package.json",
    "pom.xml",
    "pyproject.toml",
    "requirements-dev.txt",
    "requirements.txt",
    "setup.cfg",
    "setup.py",
    "tsconfig.json",
}

DOC_DIR_HINTS = {"doc", "docs"}
TEST_DIR_HINTS = {"spec", "specs", "test", "tests", "__tests__"}
SOURCE_DIR_HINTS = {"api", "app", "backend", "client", "cmd", "frontend", "internal", "lib", "pkg", "server", "src"}
DOC_BUILD_FILE_NAMES = {"makefile"}
CONFIG_NAMES = {
    ".gitlab-ci.yml",
    ".python-version",
    "docker-compose.yml",
    "docker-compose.yaml",
    "dockerfile",
    "justfile",
    "makefile",
    "procfile",
    "vercel.json",
    "netlify.toml",
}
ENTRYPOINT_NAMES = {"app", "asgi", "cli", "index", "main", "manage", "server", "wsgi"}
NON_STACK_LANGUAGE_IGNORES = {"Batchfile", "Dockerfile", "Makefile", "Roff"}

FRAMEWORK_DEPENDENCY_MAP = {
    "@nestjs/common": "NestJS",
    "@nestjs/core": "NestJS",
    "actix-web": "Actix Web",
    "angular": "Angular",
    "astro": "Astro",
    "axum": "Axum",
    "celery": "Celery",
    "django": "Django",
    "express": "Express",
    "fastapi": "FastAPI",
    "fiber": "Fiber",
    "flask": "Flask",
    "gin": "Gin",
    "gin-gonic/gin": "Gin",
    "graphql": "GraphQL",
    "mongoose": "Mongoose",
    "next": "Next.js",
    "nextjs": "Next.js",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "prisma": "Prisma",
    "pydantic": "Pydantic",
    "pytest": "Pytest",
    "react": "React",
    "scikit-learn": "scikit-learn",
    "spring-boot": "Spring Boot",
    "sqlalchemy": "SQLAlchemy",
    "streamlit": "Streamlit",
    "svelte": "Svelte",
    "tokio": "Tokio",
    "torch": "PyTorch",
    "typescript": "TypeScript",
    "uvicorn": "Uvicorn",
    "vite": "Vite",
    "vue": "Vue",
}

PACKAGE_NAME_IGNORES = {
    "build",
    "pip",
    "setuptools",
    "wheel",
}
